name: "dh-api-dev"

services:
  postgres:
    container_name: dh-api-db-dev
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dhapi'
      - 'POSTGRES_PASSWORD=localpassword'
      - 'POSTGRES_USER=dhapi'
    volumes:
      - ./docker/dev/postgres/data:/var/lib/postgresql/data
      - ./docker/dev/postgres/log:/var/log/postgresql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '8081:5432'