CREATE TABLE products_reservations
(
    product_id     BIGINT NOT NULL,
    reservation_id BIGINT NOT NULL,
    CONSTRAINT pk_products_reservations PRIMARY KEY (product_id, reservation_id)
);

CREATE TABLE reservations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    start_date         date                                    NOT NULL,
    end_date           date                                    NOT NULL,
    payment_type       VARCHAR(255)                            NOT NULL,
    creation_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

ALTER TABLE favorites
    ADD creation_data_time TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE favorites
    ALTER COLUMN creation_data_time SET NOT NULL;

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE products_reservations
    ADD CONSTRAINT fk_prores_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_reservations
    ADD CONSTRAINT fk_prores_on_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (id);
