ALTER TABLE product_category
    RENAME TO categories;

CREATE TABLE categories_features
(
    category_id BIGINT NOT NULL,
    feature_id  BIGINT NOT NULL,
    CONSTRAINT pk_categories_features PRIMARY KEY (category_id, feature_id)
);

CREATE TABLE categories_policies
(
    category_id BIGINT NOT NULL,
    policy_id   BIGINT NOT NULL,
    CONSTRAINT pk_categories_policies PRIMARY KEY (category_id, policy_id)
);

CREATE TABLE category_features
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(30)                             NOT NULL,
    description VARCHAR(300),
    icon        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category_features PRIMARY KEY (id)
);

ALTER TABLE product_policies
    RENAME TO category_policies;

ALTER TABLE categories_features
    ADD CONSTRAINT fk_catfea_on_category_feature FOREIGN KEY (feature_id) REFERENCES category_features (id);
