CREATE TABLE users_adresses
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street  VARCHAR(255)                            NOT NULL,
    city    VARCHAR(255)                            NOT NULL,
    state   VARCHAR(255)                            NOT NULL,
    zip     VARCHAR(255)                            NOT NULL,
    country VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users_adresses PRIMARY KEY (id)
);

ALTER TABLE users
    ADD address_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT uc_users_address UNIQUE (address_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES users_adresses (id);
