CREATE TABLE product_policies
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_product_policies PRIMARY KEY (id)
);

ALTER TABLE products
    ADD policy_id BIGINT;

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_POLICY FOREIGN KEY (policy_id) REFERENCES product_policies (id);